version: "3.8"
services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"

  archiver:
    build:
      context: .
      dockerfile: archiver.Dockerfile
    command: python3 -m uvicorn src.aethereal.archiver.service:app --host 0.0.0.0 --port 9020
    ports:
      - "9020:9020"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - EMBED_URL=http://some-dummy-url:8016 # This will fail gracefully
    depends_on:
      - qdrant
